export const storageKeys = {
  theme: 'back.theme',
  hapticsEnabled: 'back.hapticsEnabled',
  reduceMotionOverride: 'back.reduceMotionOverride',
  lastSoundId: 'back.lastSoundId',
  soundMuted: 'back.soundMuted',
  soundVolume: 'back.soundVolume',
  lastBreathPattern: 'back.lastBreathPattern',
  lastDistractActivity: 'back.lastDistractActivity',
  distractSfxMuted: 'back.distractSfxMuted',
  groundSfxMuted: 'back.groundSfxMuted',
  groundAmbientMuted: 'back.groundAmbientMuted',
  breatheSfxMuted: 'back.breatheSfxMuted',
  moveAmbientMuted: 'back.moveAmbientMuted',
  firstLaunchSeen: 'back.firstLaunchSeen',
  supportContact: 'back.supportContact',
  emergencyCountry: 'back.emergencyCountry',
  history: 'back.history',
  readMemory: 'back.readMemory',
  languagePreference: 'back.languagePreference',
} as const;
